import type { DashboardSummary, Item, ForecastResponse, Store } from '@/types/api'

export const mockDashboard: DashboardSummary = {
  calculationDate: '2026-03-04',
  criticalItems: [
    {
      itemId: '1',
      itemName: 'Oat Milk',
      currentQuantity: 0.5,
      unit: 'L',
      estimatedDailyConsumption: 0.3,
      estimatedDepletionDate: '2026-03-05',
      daysUntilDepletion: 1,
      percentRemaining: 12,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '2',
      itemName: 'Cat Food',
      currentQuantity: 200,
      unit: 'g',
      estimatedDailyConsumption: 80,
      estimatedDepletionDate: '2026-03-06',
      daysUntilDepletion: 2,
      percentRemaining: 20,
      calculationDate: '2026-03-04',
    },
  ],
  upcomingPurchases: [
    {
      itemId: '3',
      itemName: 'Shampoo',
      currentQuantity: 150,
      unit: 'ml',
      estimatedDailyConsumption: 15,
      estimatedDepletionDate: '2026-03-08',
      daysUntilDepletion: 4,
      percentRemaining: 35,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '4',
      itemName: 'Laundry Detergent',
      currentQuantity: 1.2,
      unit: 'kg',
      estimatedDailyConsumption: 0.08,
      estimatedDepletionDate: '2026-03-11',
      daysUntilDepletion: 7,
      percentRemaining: 48,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '5',
      itemName: 'Bread',
      currentQuantity: 3,
      unit: 'pcs',
      estimatedDailyConsumption: 0.5,
      estimatedDepletionDate: '2026-03-10',
      daysUntilDepletion: 6,
      percentRemaining: 60,
      calculationDate: '2026-03-04',
    },
  ],
  stockLevels: [],
}

export const mockStores: Store[] = [
  { id: 's1', name: 'Carrefour', visitIntervalDays: 7, lastVisitDate: '2026-03-01' },
  { id: 's2', name: 'Lidl', visitIntervalDays: 3, lastVisitDate: '2026-03-03' },
  { id: 's3', name: 'Amazon', visitIntervalDays: 14, lastVisitDate: '2026-02-20' },
]

export const mockItems: Item[] = [
  {
    id: '1',
    name: 'Oat Milk',
    category: 'BEVERAGES',
    currentQuantity: 0.5,
    unit: 'L',
    price: 89.99,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 8,
    lastBoughtDate: '2026-02-20',
    storeId: 's2',
  },
  {
    id: '2',
    name: 'Cat Food',
    category: 'PET_FOOD',
    currentQuantity: 200,
    unit: 'g',
    price: 450,
    consumerCategory: 'CAT',
    monthlyConsumptionRate: 2400,
    lastBoughtDate: '2026-02-18',
    storeId: 's1',
  },
  {
    id: '3',
    name: 'Shampoo',
    category: 'PERSONAL_CARE',
    currentQuantity: 150,
    unit: 'ml',
    price: 280,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 400,
    lastBoughtDate: '2026-01-15',
    storeId: 's3',
  },
  {
    id: '4',
    name: 'Laundry Detergent',
    category: 'CLEANING',
    currentQuantity: 1.2,
    unit: 'kg',
    price: 550,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 2.5,
    lastBoughtDate: '2026-02-01',
    storeId: 's1',
  },
  {
    id: '5',
    name: 'Bread',
    category: 'FOOD',
    currentQuantity: 3,
    unit: 'pcs',
    price: 45,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 12,
    lastBoughtDate: '2026-03-01',
    storeId: 's2',
  },
  {
    id: '6',
    name: 'Dishwasher Tablets',
    category: 'CLEANING',
    currentQuantity: 12,
    unit: 'pcs',
    price: 350,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 20,
    lastBoughtDate: '2026-02-10',
    storeId: 's1',
  },
  {
    id: '7',
    name: 'Ibuprofen 200mg',
    category: 'MEDICINE',
    currentQuantity: 16,
    unit: 'pcs',
    price: 180,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 6,
    lastBoughtDate: '2026-01-20',
    storeId: 's3',
  },
  {
    id: '8',
    name: 'Toilet Paper',
    category: 'CLEANING',
    currentQuantity: 6,
    unit: 'roll',
    price: 250,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 12,
    lastBoughtDate: '2026-02-15',
    storeId: 's2',
  },
]

export const mockForecast: ForecastResponse = {
  calculationDate: '2026-03-04',
  items: [
    {
      itemId: '1',
      itemName: 'Oat Milk',
      currentQuantity: 0.5,
      unit: 'L',
      estimatedDailyConsumption: 0.27,
      estimatedDepletionDate: '2026-03-05',
      daysUntilDepletion: 1,
      percentRemaining: 12,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '2',
      itemName: 'Cat Food',
      currentQuantity: 200,
      unit: 'g',
      estimatedDailyConsumption: 80,
      estimatedDepletionDate: '2026-03-06',
      daysUntilDepletion: 2,
      percentRemaining: 20,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '3',
      itemName: 'Shampoo',
      currentQuantity: 150,
      unit: 'ml',
      estimatedDailyConsumption: 13.3,
      estimatedDepletionDate: '2026-03-08',
      daysUntilDepletion: 4,
      percentRemaining: 35,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '4',
      itemName: 'Laundry Detergent',
      currentQuantity: 1.2,
      unit: 'kg',
      estimatedDailyConsumption: 0.083,
      estimatedDepletionDate: '2026-03-11',
      daysUntilDepletion: 7,
      percentRemaining: 48,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '5',
      itemName: 'Bread',
      currentQuantity: 3,
      unit: 'pcs',
      estimatedDailyConsumption: 0.4,
      estimatedDepletionDate: '2026-03-10',
      daysUntilDepletion: 6,
      percentRemaining: 60,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '6',
      itemName: 'Dishwasher Tablets',
      currentQuantity: 12,
      unit: 'pcs',
      estimatedDailyConsumption: 0.67,
      estimatedDepletionDate: '2026-03-22',
      daysUntilDepletion: 18,
      percentRemaining: 60,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '7',
      itemName: 'Ibuprofen 200mg',
      currentQuantity: 16,
      unit: 'pcs',
      estimatedDailyConsumption: 0.2,
      estimatedDepletionDate: '2026-04-07',
      daysUntilDepletion: 34,
      percentRemaining: 80,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '8',
      itemName: 'Toilet Paper',
      currentQuantity: 6,
      unit: 'roll',
      estimatedDailyConsumption: 0.4,
      estimatedDepletionDate: '2026-03-19',
      daysUntilDepletion: 15,
      percentRemaining: 50,
      calculationDate: '2026-03-04',
    },
  ],
}
