import type { DashboardSummary } from '@/types/api'

export const mockDashboard: DashboardSummary = {
  calculationDate: '2026-03-04',
  criticalItems: [
    {
      itemId: '1',
      itemName: 'Oat Milk',
      currentQuantity: 0.5,
      unit: 'L',
      estimatedDailyConsumption: 0.3,
      estimatedDepletionDate: '2026-03-05',
      daysUntilDepletion: 1,
      percentRemaining: 12,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '2',
      itemName: 'Cat Food',
      currentQuantity: 200,
      unit: 'g',
      estimatedDailyConsumption: 80,
      estimatedDepletionDate: '2026-03-06',
      daysUntilDepletion: 2,
      percentRemaining: 20,
      calculationDate: '2026-03-04',
    },
  ],
  upcomingPurchases: [
    {
      itemId: '3',
      itemName: 'Shampoo',
      currentQuantity: 150,
      unit: 'ml',
      estimatedDailyConsumption: 15,
      estimatedDepletionDate: '2026-03-08',
      daysUntilDepletion: 4,
      percentRemaining: 35,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '4',
      itemName: 'Laundry Detergent',
      currentQuantity: 1.2,
      unit: 'kg',
      estimatedDailyConsumption: 0.08,
      estimatedDepletionDate: '2026-03-11',
      daysUntilDepletion: 7,
      percentRemaining: 48,
      calculationDate: '2026-03-04',
    },
    {
      itemId: '5',
      itemName: 'Bread',
      currentQuantity: 3,
      unit: 'pcs',
      estimatedDailyConsumption: 0.5,
      estimatedDepletionDate: '2026-03-10',
      daysUntilDepletion: 6,
      percentRemaining: 60,
      calculationDate: '2026-03-04',
    },
  ],
  stockLevels: [],
}
