import type { DashboardSummary, Item, ForecastResponse, Store } from '@/types/api'

// Calculation date: today 2026-03-05
// daysUntilDepletion = ceil(currentQuantity / (monthlyConsumptionRate / 30))
// percentRemaining   = min(100, daysUntilDepletion / 30 * 100)

export const mockDashboard: DashboardSummary = {
  calculationDate: '2026-03-05',
  criticalItems: [
    {
      itemId: '1',
      itemName: 'Oat Milk',
      currentQuantity: 0.5,
      unit: 'L',
      estimatedDailyConsumption: 0.27,
      estimatedDepletionDate: '2026-03-07',
      daysUntilDepletion: 2,
      percentRemaining: 7,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '2',
      itemName: 'Cat Food',
      currentQuantity: 200,
      unit: 'g',
      estimatedDailyConsumption: 80,
      estimatedDepletionDate: '2026-03-08',
      daysUntilDepletion: 3,
      percentRemaining: 10,
      calculationDate: '2026-03-05',
    },
  ],
  upcomingPurchases: [
    {
      itemId: '5',
      itemName: 'Bread',
      currentQuantity: 3,
      unit: 'pcs',
      estimatedDailyConsumption: 0.4,
      estimatedDepletionDate: '2026-03-13',
      daysUntilDepletion: 8,
      percentRemaining: 27,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '3',
      itemName: 'Shampoo',
      currentQuantity: 150,
      unit: 'ml',
      estimatedDailyConsumption: 13.3,
      estimatedDepletionDate: '2026-03-17',
      daysUntilDepletion: 12,
      percentRemaining: 40,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '8',
      itemName: 'Toilet Paper',
      currentQuantity: 6,
      unit: 'roll',
      estimatedDailyConsumption: 0.4,
      estimatedDepletionDate: '2026-03-20',
      daysUntilDepletion: 15,
      percentRemaining: 50,
      calculationDate: '2026-03-05',
    },
  ],
  stockLevels: [],
}

export const mockStores: Store[] = [
  { id: 's1', name: 'Carrefour', visitIntervalDays: 7, lastVisitDate: '2026-03-01' },
  { id: 's2', name: 'Lidl', visitIntervalDays: 3, lastVisitDate: '2026-03-03' },
  { id: 's3', name: 'Amazon', visitIntervalDays: 14, lastVisitDate: '2026-02-20' },
]

export const mockItems: Item[] = [
  {
    id: '1',
    name: 'Oat Milk',
    category: 'BEVERAGES',
    currentQuantity: 0.5,
    unit: 'L',
    price: 89.99,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 8,
    autoCalc: true,
    lastBoughtDate: '2026-02-20',
    storeId: 's2',
  },
  {
    id: '2',
    name: 'Cat Food',
    category: 'PET_FOOD',
    currentQuantity: 200,
    unit: 'g',
    price: 450,
    consumerCategory: 'CAT',
    monthlyConsumptionRate: 2400,
    autoCalc: false,
    lastBoughtDate: '2026-02-18',
    storeId: 's1',
  },
  {
    id: '3',
    name: 'Shampoo',
    category: 'PERSONAL_CARE',
    currentQuantity: 150,
    unit: 'ml',
    price: 280,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 400,
    autoCalc: false,
    lastBoughtDate: '2026-01-15',
    storeId: 's3',
  },
  {
    id: '4',
    name: 'Laundry Detergent',
    category: 'CLEANING',
    currentQuantity: 1.2,
    unit: 'kg',
    price: 550,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 2.5,
    autoCalc: true,
    lastBoughtDate: '2026-02-01',
    storeId: 's1',
  },
  {
    id: '5',
    name: 'Bread',
    category: 'FOOD',
    currentQuantity: 3,
    unit: 'pcs',
    price: 45,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 12,
    autoCalc: true,
    lastBoughtDate: '2026-03-01',
    storeId: 's2',
  },
  {
    id: '6',
    name: 'Dishwasher Tablets',
    category: 'CLEANING',
    currentQuantity: 12,
    unit: 'pcs',
    price: 350,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 20,
    autoCalc: false,
    lastBoughtDate: '2026-02-10',
    storeId: 's1',
  },
  {
    id: '7',
    name: 'Ibuprofen 200mg',
    category: 'MEDICINE',
    currentQuantity: 16,
    unit: 'pcs',
    price: 180,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 6,
    autoCalc: false,
    lastBoughtDate: '2026-01-20',
    storeId: 's3',
  },
  {
    id: '8',
    name: 'Toilet Paper',
    category: 'CLEANING',
    currentQuantity: 6,
    unit: 'roll',
    price: 250,
    consumerCategory: 'ADULT',
    monthlyConsumptionRate: 12,
    autoCalc: true,
    lastBoughtDate: '2026-02-15',
    storeId: 's2',
  },
  {
    id: '9',
    name: 'Olive Oil',
    category: 'FOOD',
    currentQuantity: 0.7,
    unit: 'L',
    price: 320,
    consumerCategory: 'ADULT',
    // no monthlyConsumptionRate → "No forecast" in UI
    lastBoughtDate: '2026-02-25',
    storeId: 's1',
  },
]

// Forecast only for items with monthlyConsumptionRate set.
// Formula: daily = rate/30, days = ceil(qty/daily), percent = min(100, days/30*100)
// Item 1 (Oat Milk):          ceil(0.5  / 0.267)  = 2   days, percent =  7%
// Item 2 (Cat Food):          ceil(200  / 80)      = 3   days, percent = 10%
// Item 3 (Shampoo):           ceil(150  / 13.33)   = 12  days, percent = 40%
// Item 4 (Laundry Detergent): ceil(1.2  / 0.0833)  = 15  days, percent = 50%
// Item 5 (Bread):             ceil(3    / 0.4)     = 8   days, percent = 27%
// Item 6 (Dishwasher Tablets):ceil(12   / 0.667)   = 18  days, percent = 60%
// Item 7 (Ibuprofen):         ceil(16   / 0.2)     = 80  days, percent = 100%
// Item 8 (Toilet Paper):      ceil(6    / 0.4)     = 15  days, percent = 50%
// Item 9 (Olive Oil):         no rate → excluded
export const mockForecast: ForecastResponse = {
  calculationDate: '2026-03-05',
  items: [
    {
      itemId: '1',
      itemName: 'Oat Milk',
      currentQuantity: 0.5,
      unit: 'L',
      estimatedDailyConsumption: 0.27,
      estimatedDepletionDate: '2026-03-07',
      daysUntilDepletion: 2,
      percentRemaining: 7,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '2',
      itemName: 'Cat Food',
      currentQuantity: 200,
      unit: 'g',
      estimatedDailyConsumption: 80,
      estimatedDepletionDate: '2026-03-08',
      daysUntilDepletion: 3,
      percentRemaining: 10,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '3',
      itemName: 'Shampoo',
      currentQuantity: 150,
      unit: 'ml',
      estimatedDailyConsumption: 13.33,
      estimatedDepletionDate: '2026-03-17',
      daysUntilDepletion: 12,
      percentRemaining: 40,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '4',
      itemName: 'Laundry Detergent',
      currentQuantity: 1.2,
      unit: 'kg',
      estimatedDailyConsumption: 0.083,
      estimatedDepletionDate: '2026-03-20',
      daysUntilDepletion: 15,
      percentRemaining: 50,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '5',
      itemName: 'Bread',
      currentQuantity: 3,
      unit: 'pcs',
      estimatedDailyConsumption: 0.4,
      estimatedDepletionDate: '2026-03-13',
      daysUntilDepletion: 8,
      percentRemaining: 27,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '6',
      itemName: 'Dishwasher Tablets',
      currentQuantity: 12,
      unit: 'pcs',
      estimatedDailyConsumption: 0.67,
      estimatedDepletionDate: '2026-03-23',
      daysUntilDepletion: 18,
      percentRemaining: 60,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '7',
      itemName: 'Ibuprofen 200mg',
      currentQuantity: 16,
      unit: 'pcs',
      estimatedDailyConsumption: 0.2,
      estimatedDepletionDate: '2026-05-24',
      daysUntilDepletion: 80,
      percentRemaining: 100,
      calculationDate: '2026-03-05',
    },
    {
      itemId: '8',
      itemName: 'Toilet Paper',
      currentQuantity: 6,
      unit: 'roll',
      estimatedDailyConsumption: 0.4,
      estimatedDepletionDate: '2026-03-20',
      daysUntilDepletion: 15,
      percentRemaining: 50,
      calculationDate: '2026-03-05',
    },
  ],
}
